# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
   os: ubuntu-24.04
   tools:
      python: "3.14"
   jobs:
      create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
         - uv venv
      install:
         - uv install
      build:
         html:
            - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
#formats:
#  - pdf
