# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
   os: ubuntu-24.04
   apt_packages:
     - python3-lxml
   tools:
      python: "3.12"
   jobs:
      create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
         - uv venv --python 3.12
      install:
         - uv pip install --group docs
      build:
         html:
            - uv run sphinx-build -c ./source/conf.py -T -b html docs $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
#sphinx:
#  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
#formats:
#  - pdf
